---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

## Installation

You can install the development version from Github:

```{r,eval=FALSE}
if (!require("remotes")) install.packages("remotes")
remotes::install_github("toledo60/OptimFunctions")
```

## Overview

```{r}
library(OptimFunctions)
```

This package is for research purposes only, all functions/code were obtain from [Virtual Library of Simulation Experiments](https://www.sfu.ca/~ssurjano/optimization.html).

Currently `OptimFunctions` has the following test functions: 

```{r,echo=FALSE}
fns_table <- tibble::tribble( ~Function, ~Category, ~ Dimension,
                              'Ackley', 'Many-local-minima','d',
                              'Levy','Many-local-minima', 'd',
                              'EggHolder','Many-local-minima','2',
                              'Rastrigin','Many-local-minima', 'd',
                              'Schwefel', 'Many-local-minima','d',
                              'Trid', 'Bowl-shaped', 'd',
                              'Zakharov', 'Plate-shaped','d',
                              'Matya', 'Plate-shaped','2',
                              'Branin', 'Other', '2',
                              'Hartmann', 'Other', '3,4,6')
knitr::kable(fns_table,align = 'c')
```
